language:node_js
sudo:false
node_js:
  - '4.3.2'
  - '4.4.1'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
    - npm install --verbose
script:
  - npm run test
notifications:
  slack: yytspace:mAvt46hmfFsPbipu3auvoUH3
